apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app-container
          image: localhost:5000/docker-java-jar:latest
          ports:
            - containerPort: 80