---
- name: Download VirtualBox Installer
  win_command: "powershell -Command \"Invoke-WebRequest -Uri 'https://download.virtualbox.org/virtualbox/6.1.28/VirtualBox-6.1.28-147628-Win.exe' -OutFile 'C:\\k8s\\VirtualBox-Installer.exe'\""


- name: Install VirtualBox
  win_command: C:\Temp\VirtualBox-Installer.exe -s
  async: 3000
  poll: 0
  become: yes

- name: Clean Up Installer
  win_command: Remove-Item -Path "C:\Temp\VirtualBox-Installer.exe" -Force


