- name: Install Kubernetes | K8s init
  shell: |
    sudo apt update && \
    sudo apt install kubelet kubeadm kubectl -y && \
    sudo apt-mark hold kubelet kubeadm kubectl

- name: k8s Configuration | Prepare Manager | Create Worker Node Join Token
  shell: |
    kubeadm init --control-plane-endpoint=master
  ignore_errors: yes
  register: worker_token
  when: manager is defined and manager

- name: Display the captured output
  debug:
    var: worker_token.stdout

- name:  Install Kubernetes Cluster with Kubeadm | K8s init
  shell: |
    mkdir -p $HOME/.kube && \
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && \
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
  when: manager is defined and manager

- name:  settings node | K8s init
  shell: "{{ worker_token.stdout_lines }}"
  when: node is defined and node

- name: K8S Copy Deployment Calico File | K8s init
  template:
    src: "calico.yml"
    dest: /opt/project/calico.yml

- name: k8s calico deployment | K8s init
  shell: cd /opt/project && kubectl apply -f calico.yaml

- name: K8S Copy Deployment File | K8s init
  template:
    src: "deployment.yml"
    dest: /opt/project/deployment.yml

- name: k8s deployment | K8s init
  shell: cd /opt/project && kubectl apply -f deployment.yaml


